kind: pipeline
name: default

steps:
- name: build
  image: plugins/hugo
  settings:
    validate: true

- name: deploy
  image: jhauer1/hugo-build-deploy:v0.0.1
  environment:
    AWS_DEFAULT_REGION:
      from_secret: AWS_DEFAULT_REGION
    AWS_DEFAULT_REGION:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_DEFAULT_REGION:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - hugo deploy --target=mydeployment
